services:
  - type: web
    name: employee-manager
    env: node
    rootDir: server
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
